# Generated by Django 5.1.3 on 2024-12-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_cliente_user_cliente_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default=12345678, max_length=100),
            preserve_default=False,
        ),
    ]
